### ISSUE TITLE
This method has been removed in JSZip 3.0, please check the upgrade guide.

### ISSUE THREAD

**Issue by Wizzercn** [bsegault/zip-zip-top#2]
var data = this.generate({type:"nodebuffer", compression: "DEFLATE"});

so..

**Comment by bsegault** [comment]
Hi,
Thanks for notifying!
I just pushed a `jszip3` branch as a quick fix. I made simple tests and it should now work with JSZip3.

I will try to further investigate JSZip 3.0 changes, and adapt ZipZipTop as needed.

If there are no problem, I will merge the `jszip3` branch soon, and release it to npm as well =)
